name: test

on:
  push:
    branches:
      - enable-aws-assume 

permissions:
  id-token: write
  contents: read

jobs:
  draft-a-release:
    name: Draft a release
    if: github.repository == 'peterzhuamazon/opensearch-migrations'
    runs-on: ubuntu-latest
    steps:
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.MIGRATIONS_DOCKER_ROLE }}
          aws-region: us-east-1
      - name: Retrieve Values
        run: |
          export DOCKERHUB_PASSWORD=`aws secretsmanager get-secret-value --secret-id jenkins-staging-dockerhub-credential --query SecretString --output text`
          echo "::add-mask::$DOCKERHUB_PASSWORD"
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_PASSWORD }}
      - name: Logout to DockerHub
        if: always()
        run: docker logout
