name: test

on:
  push:
    branches:
      - enable-aws-assume 

permissions:
  id-token: write
  contents: read

jobs:
  draft-a-release:
    name: Draft a release
    if: github.repository == 'peterzhuamazon/opensearch-migrations'
    outputs:
      DOCKERHUB_PASSWORD: ${{ steps.step-build-test-linux.outputs.DOCKERHUB_PASSWORD }}
    runs-on: ubuntu-latest
    steps:
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.MIGRATIONS_DOCKER_ROLE }}
          aws-region: us-east-1
      - name: Retrieve Values
        id: retrieve-values
        run: |
          echo "DOCKERHUB_PASSWORD=`aws secretsmanager get-secret-value --secret-id jenkins-staging-dockerhub-credential --query SecretString --output text`" >> $GITHUB_OUTPUT
          echo "::add-mask::${{ steps.retrieve-value.outputs.DOCKERHUB_PASSWORD }}"
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ steps.retrieve-value.outputs.DOCKERHUB_PASSWORD }}
      - name: Logout to DockerHub
        if: always()
        run: docker logout
